esphome:
  name: $name
  friendly_name: $friendly_name
  name_add_mac_suffix: true
  platform: ESP8266
  board: nodemcuv2
  esp8266_restore_from_flash: true
  project:
    name: $project_name
    version: $project_version
  on_boot:
    priority: 800.0
    then:
      - text_sensor.template.publish:
          id: device_id
          state: !lambda 'return get_mac_address();'

substitutions:
  status_led_inverted: "true"

# overrides the MDNS component to add a Konnected service
external_components:
  - source: github://drothenberger/konnected-esphome@white/deploy
    components: [ mdns ]

text_sensor:
  - platform: template
    name: Device ID
    id: device_id
    entity_category: diagnostic
    update_interval: never
  - platform: version
    name: ESPHome Version
    hide_timestamp: true
    
sensor:
  - platform: uptime
    name: Uptime
    entity_category: diagnostic
    
button:
  - platform: restart
    name: Restart
    entity_category: config